Hw4
Shut-Oleg/GeekHub pull request #9
Opened 2018-11-20 20:35 UTC by Shut-Oleg

Хочу показати частину своєї роботи...

2018-12-03 14:40 UTC, Shut-Oleg commented
Done.

2018-12-09 16:50 UTC, yana-tsylinska requested changes

2018-12-09 16:50 UTC, yana-tsulya commented on HW4/app/index.html
> +                    <p>Download now</p>
а навіщо тут ще параграф?)

2018-12-09 16:50 UTC, yana-tsulya commented on HW4/app/index.html
> +            <h3 class="header3">What people say <span class="red">.</span></h3>
точки краще через ::after добавляти)

2018-12-09 16:50 UTC, yana-tsulya commented on HW4/app/index.html
> +                        <svg class="svgicon_left" version="1.1" id="Icons_-_48px" xmlns="http://www.w3.org/2000/svg"
спробуй іконки не інланом додати, а через svg:use ;)

2018-12-09 16:50 UTC, yana-tsulya commented on HW4/app/sass/_mobile-responsive.scss
> +      padding-bottom: 80px;
тут скоріше марджін потрібно використовувати )

2018-12-09 16:50 UTC, yana-tsulya commented on HW4/app/sass/_mobile-responsive.scss
> +      padding-bottom: 100px;
те саме))

2018-12-09 16:50 UTC, yana-tsulya commented on HW4/app/sass/main.scss
> +    display: none;
не варто так ховати, почитай тут - https://htmlacademy.ru/shorts/12

2018-12-30 17:44 UTC, merged